### ISSUE TITLE
Error while using -r option

### ISSUE THREAD

**Issue by apn83** [lim74/LncDC#1]
Hi, 
I tried to predict lncrna with secondary structure -r option. I already trained the model with my data. 

There were several warnings like 

> WARNING: vrna_fold_compound@data_structures.c: sequence length of 33176 exceeds addressable range

After 100% of calculations complete, the program faced the following issue before it died.

> File "/ibex/scratch/projects/c2078/amd/LNCRNA/LncDC/bin/SSF_extraction.py", line 52, in ss_kmer_ratio
>     ss_score = sum_log_ratio/ss_num
> ZeroDivisionError: division by zero

What causes this issue?
Thanks in advance.

Arun

**Comment by lim74** [comment]
Hi Arun,

Thanks for using LncDC! The issue is that the RNAfold program cannot calculate secondary structures if the transcript is too long. I have added a constraint of sequence length to no more than 20,000 nt if using secondary structure features for lncRNA prediction. 

We limit sequence length to 20,000 nt because most annotated lncRNAs are shorter than 20,000 nt. For instance, only 15 out of 48,479 (0.03%) lncRNAs are longer than 20,000 nt in the GENCODE database (human release 34). If some of your candidate sequences are longer than 20,000 nt, you can use LncDC without the '-r' option for prediction. 

The program is updated and a new version has been released. If you don't want to set up the program again, you only need to download two files, bin/lncDC.py and bin/lncDC-train.py, and move them to the bin/ directory of the LncDC you installed.

Feel free to let me know if you find any other issues. Your advice will be helpful for the improvement of LncDC!

Best,
Minghua

**Comment by apn83** [comment]
> Hi Arun,
> 
> Thanks for using LncDC! The issue is that the RNAfold program cannot calculate secondary structures if the transcript is too long. I have added a constraint of sequence length to no more than 20,000 nt if using secondary structure features for lncRNA prediction.
> 
> We limit sequence length to 20,000 nt because most annotated lncRNAs are shorter than 20,000 nt. For instance, only 15 out of 48,479 (0.03%) lncRNAs are longer than 20,000 nt in the GENCODE database (human release 34). If some of your candidate sequences are longer than 20,000 nt, you can use LncDC without the '-r' option for prediction.
> 
> The program is updated and a new version has been released. If you don't want to set up the program again, you only need to download two files, bin/lncDC.py and bin/lncDC-train.py, and move them to the bin/ directory of the LncDC you installed.
> 
> Feel free to let me know if you find any other issues. Your advice will be helpful for the improvement of LncDC!
> 
> Best, Minghua

Hi Minghua,
In the new version, you mean you have removed the constraint of sequence length? i.e. I can include sequences longer than 20k nt?
Thanks,
Arun

**Comment by apn83** [comment]
Ah.. got it. Now you have included an else to filter out transcripts with length > 20knt !

**Comment by lim74** [comment]
Exactly!
