### ISSUE TITLE
Test data error

### ISSUE THREAD

**Issue by wyim-pgl** [lim74/LncDC#2]
I've got below error with test set.
Do you have any recommendations?

`python bin/lncDC.py -i test/mouse_test_toy.fasta -o lncdc_mouse.csv -r -t 8`

```bash
Process Start.
Checking if the inputfile exists ...
Checking if the model file and other required files exist ...
Checking if the inputfile is in fasta format ...
PASS

Initializing dataframe ...
Total Number of transcripts loaded: 200
Calculating transcript lengths ...

Removing Non-valid transcripts (sequence that have non-ATGCatgc letters & sequence length less than 200 nt) ...
Filtering out transcripts with sequence length greater than 20,000nt due to the limited addressable range of the RNAfold program ...
We recommand you use LncDC without the '-r' option to predict lncRNAs over 20,000 nts.

Number of valid transcripts: 200

Extracting SIF and PF features ...
Calculating secondary structures of the transcripts by RNAfold ... (This process may take a long time!)
Total number of dataframe chunks divided: 80
Chunks of secondary structure calculation finished:
100%|█████████████████████████████████████████████████████████████████████████████████████| 80/80 [11:02<00:00,  8.28s/it]
Extracting SSF features ...
Traceback (most recent call last):
  File "/data/gpfs/assoc/pgl/bin/LncDC/bin/lncDC.py", line 432, in <module>
    main()
  File "/data/gpfs/assoc/pgl/bin/LncDC/bin/lncDC.py", line 405, in main
    x_test[x_test.columns] = pickle_imputer.transform(x_test[x_test.columns])
  File "/data/gpfs/home/wyim/.local/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 142, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/data/gpfs/home/wyim/.local/lib/python3.9/site-packages/sklearn/impute/_base.py", line 564, in transform
    if self.strategy == "constant" or self.keep_empty_features:
AttributeError: 'SimpleImputer' object has no attribute 'keep_empty_features'

```

**Comment by lim74** [comment]
Hi Won,

Can you please check out the version of scikit-learn? The error is likely caused by an incompatible version of scikit-learn. The default model of LncDC was trained under scikit-learn == 1.1.3, so that if you used a different version of scikit-learn, the default model could not be applied correctly. 

If you are using conda, you can issue the following command to check the version of scikit-learn. If you created a conda environment for LncDC, please make sure it is activated.
 
`conda list scikit-learn`

If the version of scikit-learn is different from 1.1.3, please update it to 1.1.3. You can run this code if you use conda:

`conda install scikit-learn=1.1.3`

Let me know if this works for you.

Best,
Minghua

**Comment by wyim-pgl** [comment]
Thanks Minghua,
I installed with following commands and it has specific version scikit-learn=1.1.3.
However the error is still persistent.
`
mamba create -n lncrna python=3.9  scikit-learn=1.1.3 tqdm=4.64 pandas=1.5 numpy=1.23 biopython=1.79 xgboost=1.7.1 imbalanced-learn=0.9.1 viennarna -y
`
I installed it with pip, now it is working.

In addition, I am trying to train plant specific model. The coding file includes 7.5Gb and lncrna is 322Mb.
Is it possible to run?

Thanks.

**Comment by lim74** [comment]
Sure, you can do that. 

LncDC will automatically balance training data by both under- and over-sampling strategies. Since the number of your mRNAs is much greater than lncRNAs, LncDC will randomly under-sampling mRNAs and use a SMOTE approach to over-sampling your lncRNAs, leading to a balanced training dataset. This process is automatically conducted and there are no extra parameters required.
